# Generated by Django 2.0.13 on 2019-04-12 07:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise4', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persondetail',
            name='profilepicture',
            field=models.ImageField(blank=True, default='gallery/default.png', null=True, upload_to='gallery'),
        ),
        migrations.AlterField(
            model_name='persondetail',
            name='contact_number',
            field=models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: "+639XXXXXXXXX". (x represents a number)', regex='^\\+639\\d{9}$')]),
        ),
    ]
